.....FF.
======================================================================
FAIL: test_filter_6 (ClassEval_0_0.AccessGatewayFilterTestFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 106, in test_filter_6
    self.assertFalse(res)
AssertionError: True is not false

======================================================================
FAIL: test_filter_7 (ClassEval_0_0.AccessGatewayFilterTestFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 115, in test_filter_7
    self.assertIsNone(res)
AssertionError: True is not None

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
.F.FF
======================================================================
FAIL: test_is_start_with_2 (ClassEval_0_0.AccessGatewayFilterTestIsStartWith)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 138, in test_is_start_with_2
    self.assertFalse(res)
AssertionError: True is not false

======================================================================
FAIL: test_is_start_with_4 (ClassEval_0_0.AccessGatewayFilterTestIsStartWith)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 150, in test_is_start_with_4
    self.assertFalse(res)
AssertionError: True is not false

======================================================================
FAIL: test_is_start_with_5 (ClassEval_0_0.AccessGatewayFilterTestIsStartWith)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 156, in test_is_start_with_5
    self.assertFalse(res)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=3)
....F
======================================================================
FAIL: test_get_jwt_user_5 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_0_0.py", line 193, in test_get_jwt_user_5
    self.assertIsNone(res)
AssertionError: {'user': {'name': 'user1'}} is not None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
EEF..
======================================================================
ERROR: test_parse_arguments_1 (ClassEval_2_0.ArgumentParserTestParseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 107, in test_parse_arguments_1
    result, missing_args = self.parser.parse_arguments(command_str)
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 40, in parse_arguments
    value = args_list[i + 1]  # Extracting argument value
IndexError: list index out of range

======================================================================
ERROR: test_parse_arguments_2 (ClassEval_2_0.ArgumentParserTestParseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 120, in test_parse_arguments_2
    result, missing_args = self.parser.parse_arguments(command_str)
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 40, in parse_arguments
    value = args_list[i + 1]  # Extracting argument value
IndexError: list index out of range

======================================================================
FAIL: test_parse_arguments_3 (ClassEval_2_0.ArgumentParserTestParseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 135, in test_parse_arguments_3
    self.assertFalse(result)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.E...
======================================================================
ERROR: test_convert_type_2 (ClassEval_2_0.ArgumentParserTestConvertType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 255, in test_convert_type_2
    result = self.parser._convert_type("age", "twenty-five")
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 91, in _convert_type
    return self.types[arg](value)
ValueError: invalid literal for int() with base 10: 'twenty-five'

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=1)
F
======================================================================
FAIL: test_main (ClassEval_2_0.ArgumentParserTestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_2_0.py", line 288, in test_main
    self.assertEqual(parser.arguments, arguments)
AssertionError: {'option1': '-arg2', 'value': '-option2'} != {'arg1': 21, 'option1': True, 'arg2': 'value', 'option2': True}
- {'option1': '-arg2', 'value': '-option2'}
+ {'arg1': 21, 'arg2': 'value', 'option1': True, 'option2': True}

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF.FF
======================================================================
FAIL: test_count_all_1 (ClassEval_3_0.ArrangementCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 113, in test_count_all_1
    self.assertEqual(res, 64)
AssertionError: 16 != 64

======================================================================
FAIL: test_count_all_2 (ClassEval_3_0.ArrangementCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 117, in test_count_all_2
    self.assertEqual(res, 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_count_all_4 (ClassEval_3_0.ArrangementCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 125, in test_count_all_4
    self.assertEqual(res, 15)
AssertionError: 8 != 15

======================================================================
FAIL: test_count_all_5 (ClassEval_3_0.ArrangementCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 129, in test_count_all_5
    self.assertEqual(res, 325)
AssertionError: 32 != 325

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFFF
======================================================================
FAIL: test_select_1 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 137, in test_select_1
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), ([49 chars], 3)] != [[1, 2], [1, 3], [1, 4], [2, 1], [2, 3], [[49 chars], 3]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2),
?  ^    ^

+ [[1, 2],
?  ^    ^

-  (1, 3),
?  ^    ^

+  [1, 3],
?  ^    ^

-  (1, 4),
?  ^    ^

+  [1, 4],
?  ^    ^

-  (2, 1),
?  ^    ^

+  [2, 1],
?  ^    ^

-  (2, 3),
?  ^    ^

+  [2, 3],
?  ^    ^

-  (2, 4),
?  ^    ^

+  [2, 4],
?  ^    ^

-  (3, 1),
?  ^    ^

+  [3, 1],
?  ^    ^

-  (3, 2),
?  ^    ^

+  [3, 2],
?  ^    ^

-  (3, 4),
?  ^    ^

+  [3, 4],
?  ^    ^

-  (4, 1),
?  ^    ^

+  [4, 1],
?  ^    ^

-  (4, 2),
?  ^    ^

+  [4, 2],
?  ^    ^

-  (4, 3)]
?  ^    -

+  [4, 3]]
?  ^     +


======================================================================
FAIL: test_select_2 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 143, in test_select_2
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] != [[1, 2], [1, 3], [2, 1], [2, 3], [3, 1], [3, 2]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^    -

+ [[1, 2], [1, 3], [2, 1], [2, 3], [3, 1], [3, 2]]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^     +


======================================================================
FAIL: test_select_3 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 149, in test_select_3
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(2, 3), (2, 4), (3, 2), (3, 4), (4, 2), (4, 3)] != [[2, 3], [2, 4], [3, 2], [3, 4], [4, 2], [4, 3]]

First differing element 0:
(2, 3)
[2, 3]

- [(2, 3), (2, 4), (3, 2), (3, 4), (4, 2), (4, 3)]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^    -

+ [[2, 3], [2, 4], [3, 2], [3, 4], [4, 2], [4, 3]]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^     +


======================================================================
FAIL: test_select_4 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 155, in test_select_4
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (2, 1)] != [[1, 2], [2, 1]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (2, 1)]
?  ^    ^  ^    -

+ [[1, 2], [2, 1]]
?  ^    ^  ^     +


======================================================================
FAIL: test_select_5 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 161, in test_select_5
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (3,), (4,)] != [[1], [2], [3], [4]]

First differing element 0:
(1,)
[1]

- [(1,), (2,), (3,), (4,)]
+ [[1], [2], [3], [4]]

======================================================================
FAIL: test_select_6 (ClassEval_3_0.ArrangementCalculatorTestSelect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 167, in test_select_6
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (2, 1)] != [[1, 2], [2, 1]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (2, 1)]
?  ^    ^  ^    -

+ [[1, 2], [2, 1]]
?  ^    ^  ^     +


----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_select_all_1 (ClassEval_3_0.ArrangementCalculatorTestSelectAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 176, in test_select_all_1
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (3,), (1, 2), (1, 3), (2, 1),[85 chars], 1)] != [[1], [2], [3], [1, 2], [1, 3], [2, 1], [2[82 chars], 1]]

First differing element 0:
(1,)
[1]

Diff is 652 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_select_all_2 (ClassEval_3_0.ArrangementCalculatorTestSelectAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 183, in test_select_all_2
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (4,), (1, 2), (1, 4), (2, 1),[85 chars], 1)] != [[1], [2], [4], [1, 2], [1, 4], [2, 1], [2[82 chars], 1]]

First differing element 0:
(1,)
[1]

Diff is 652 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_select_all_3 (ClassEval_3_0.ArrangementCalculatorTestSelectAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 189, in test_select_all_3
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (1, 2), (2, 1)] != [[1], [2], [1, 2], [2, 1]]

First differing element 0:
(1,)
[1]

- [(1,), (2,), (1, 2), (2, 1)]
+ [[1], [2], [1, 2], [2, 1]]

======================================================================
FAIL: test_select_all_4 (ClassEval_3_0.ArrangementCalculatorTestSelectAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 195, in test_select_all_4
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (3,), (1, 3), (3, 1)] != [[1], [3], [1, 3], [3, 1]]

First differing element 0:
(1,)
[1]

- [(1,), (3,), (1, 3), (3, 1)]
+ [[1], [3], [1, 3], [3, 1]]

======================================================================
FAIL: test_select_all_5 (ClassEval_3_0.ArrangementCalculatorTestSelectAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 201, in test_select_all_5
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,)] != [[1]]

First differing element 0:
(1,)
[1]

- [(1,)]
+ [[1]]

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_arrangementcalculator (ClassEval_3_0.ArrangementCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gideonpeters/Documents/SE4AI/SOEN691/ClassEval/classeval_evaluation/ClassEval_3_0.py", line 232, in test_arrangementcalculator
    self.assertEqual(res, 64)
AssertionError: 16 != 64

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
